/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 2f851d060019fcc6a6fc064891701cd3)
interface __BaseEnv_Env {
	SESSION: KVNamespace;
	CUSTOMER_RATE_LIMITER: RateLimit;
	IMAGES: ImagesBinding;
	ASSETS: Fetcher;
}
declare namespace Cloudflare {
	interface StagingEnv {
		SESSION: KVNamespace;
		CUSTOMER_RATE_LIMITER: RateLimit;
		IMAGES: ImagesBinding;
		ASSETS: Fetcher;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
